local g = vim.g

g.loaded_tutor = 1
g.loaded_spec = 1
g.loaded_2html_plugin      = 1 
g.loaded_getscript         = 1 
g.loaded_getscriptPlugin   = 1 
g.loaded_gzip              = 1 
g.loaded_logipat           = 1 
g.loaded_logiPat           = 1 
g.loaded_matchparen        = 1 
g.loaded_netrw             = 1 
g.loaded_netrwFileHandlers = 1 
g.loaded_netrwPlugin       = 1 
g.loaded_netrwSettings     = 1 
g.loaded_rrhelper          = 1 
g.loaded_spellfile_plugin  = 1 
g.loaded_sql_completion    = 1 
g.loaded_syntax_completion = 1 
g.loaded_tar               = 1 
g.loaded_tarPlugin         = 1 
g.loaded_vimball           = 1 
g.loaded_vimballPlugin     = 1 
g.loaded_zip               = 1 
g.loaded_zipPlugin         = 1 
g.vimsyn_embed             = 1 
